apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox
  namespace: default
  annotations:
    app.kubernetes.io/artifact-info: '{"name":"busybox","image":"busybox:1.35.0","version":"1.35.0","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203082335","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-08T23:35:43+11:00","changeRef":"CRQ000019921","output":"../shores-helm/charts"}'

  labels:
    app.kubernetes.io/instance: 'busybox'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'busybox'
    app.kubernetes.io/release: 'busybox'
    app.kubernetes.io/version: '1.35.0'
    helm.sh/chart: 'busybox-1.35.0'


