apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  annotations:
    app.kubernetes.io/artifact-info: '{"name":"nginx","image":"nginx:1.21.6","version":"1.21.6","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203081904","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-08T19:04:20+11:00","changeRef":"CRQ000019921"}'

  labels:
    app.kubernetes.io/instance: 'nginx'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'nginx'
    app.kubernetes.io/release: 'nginx'
    app.kubernetes.io/version: '1.21.6'
    helm.sh/chart: 'nginx-1.21.6'

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: nginx

    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          image: nginx:1.21.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: "PROXY_HOST"
              value: "http://localhost:8080"
            - name: "PROXY_PORT"
              value: "-1"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-cache-nginx
              mountPath: /var/cache/nginx
            - name: var-run
              mountPath: /var/run

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector:
        eks.amazonaws.com/nodegroup: tools

      affinity: { }
      tolerations: [ ]
      volumes:
        - name: tmp
          emptyDir: { }
        - name: var-cache-nginx
          emptyDir: { }
        - name: var-run
          emptyDir: { }
