apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: default
  annotations:
    app.kubernetes.io/artifact-info: '{"name":"nginx","image":"nginx:1.21.6","version":"1.21.6","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203090000","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-09T00:00:39+11:00","changeRef":"CRQ000019921","output":"../shores-helm/charts"}'

  labels:
    app.kubernetes.io/instance: 'nginx'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'nginx'
    app.kubernetes.io/release: 'nginx'
    app.kubernetes.io/version: '1.21.6'
    helm.sh/chart: 'nginx-1.21.6'


