apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo
  namespace: default
  annotations:
    app.kubernetes.io/artifact-info: '{"name":"todo","image":"skhatri/todo:0.1","version":"0.1","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203090000","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-09T00:00:39+11:00","changeRef":"CRQ000019921","output":"../shores-helm/charts"}'

  labels:
    app.kubernetes.io/instance: 'todo'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'todo'
    app.kubernetes.io/release: 'todo'
    app.kubernetes.io/version: '0.1'
    helm.sh/chart: 'todo-0.1'


