apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: default
  annotations: 
    app.kubernetes.io/artifact-info: '{"name":"todo","image":"todo:0.1","version":"0.1","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203082356","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-08T23:56:02+11:00","changeRef":"CRQ000019921","output":"../shores-helm/charts"}'

  labels: 
    app.kubernetes.io/instance: 'todo'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'todo'
    app.kubernetes.io/release: 'todo'
    app.kubernetes.io/version: '0.1'
    helm.sh/chart: 'todo-0.1'

spec:
  type: ClusterIP
  ports: 

    - name: http
      port: 8080
      targetPort: http
      protocol: TCP

  selector:
    app.kubernetes.io/instance: todo
    app.kubernetes.io/name: todo


