apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: default
  annotations:
    app.kubernetes.io/artifact-info: '{"name":"todo","image":"skhatri/todo:0.1","version":"0.1","namespace":"default"}'
    app.kubernetes.io/deployment-info: '{"user":"skhatri","releaseId":"202203090000","action":"deploy","command":"deploy spec/user/release-set/release-1.yaml","created":"2022-03-09T00:00:39+11:00","changeRef":"CRQ000019921","output":"../shores-helm/charts"}'

  labels:
    app.kubernetes.io/instance: 'todo'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'todo'
    app.kubernetes.io/release: 'todo'
    app.kubernetes.io/version: '0.1'
    helm.sh/chart: 'todo-0.1'

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: todo
      app.kubernetes.io/name: todo

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: todo
        app.kubernetes.io/name: todo

    spec:
      serviceAccountName: todo
      containers:
        - name: todo
          image: skhatri/todo:0.1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          env:
            - name: "PROXY_HOST"
              value: "http://localhost:8080"
            - name: "PROXY_PORT"
              value: "-1"
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector:
        eks.amazonaws.com/nodegroup: tools

      affinity: { }
      tolerations: [ ]
      volumes:
        - name: tmp-volume
          emptyDir: { }
